services:
  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s


    networks:
      - fastapi
  fastapi:
    build: .
    depends_on:
      db:
        condition: service_healthy

    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: example
    networks:
      - fastapi

networks:
  fastapi:
